Doc2Door/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('app.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from .views import *

app_name = 'app'


urlpatterns = [
    path('home/' ,Home , name='home' ),
    path('contact/' , contact , name="contact"),

    path('logout/' ,Logout_view , name='logout' ),
    path('loginPhone/' , login_phone , name='loginPhone'),
    path('verify_login_phone/' , verify_login_phone , name='verify_login_phone'),
    path('loginPhoneDoctor/' , login_phone_doctor , name='loginPhoneDoctor'),
    path('verify_login_phone_doctor/' , verify_login_phone_doctor , name='verify_login_phone_doctor'),

    path('updateProfile/' , ProfileUpdate ,name='ProfileUpdate'),
    path('profile/' , profile_view ,name='profile'),

    path('post/',postView , name="postView"),
    path('singlePost/<str:slug>' ,singlePost , name='singlePost' ),
    path('category/<str:slug>', category ,name="category"),

    path('news/',newsView , name="newsView"),
    path('singleNews/<str:slug>',singleNews , name="singleNews"),

    path('reservationView/<int:id>' , reservationView , name='reservationView'),
    path('showReservation/' , showReservation , name="showReservation"),
    path('reservationRequest/<int:id>' , reservationRequest , name='reservationRequest'), 
    path('detailReserve/' , detailReserve , name="detailReserve"),
    path('detailUserResreve/' , detailUserResreve , name="detailUserResreve"),
    path('detailDoctor/<int:id>' , detailDoctor , name='detailDoctor'),

    path('deleteCartView/<int:id>' , deleteCartView , name='deleteCartView'),
    path('cartView/' , cartView , name='cartView'),

    path('send_request/', request_payment, name='request'),
    path('verify/', verify , name='verify'),

    path('test/' , test , name='tset')
]

app/templates/app/old/reserve/reservation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <p>
            city:
            <input type="text" name="city">
        </p>
        <p>
            address:
            <input type="text" name="address">
        </p>
        <p>
            plate:
            <input type="text" name="plate">
        </p>
        <p>
            name:
            <input type="text" name="name">
        </p>
        <p>
            insurance:
            <input type="text" name="insurance">
        </p>
        <p>
            <input type="submit">
        </p>
    </form>
    <p>
        {% for reserve in reserve %}
            <p>
                {{ reserve.post.title }}
            </p>
            <p>
                {{ reserve.post.price }}
            </p>
        {% endfor %}
    </p>
</body>
</html>

app/templates/app/old/reserve/show_reservation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for reserv in reserv %}
    <p>
        شماره رزرو کننده
        {{ reserv.user.phone }}
    </p>
    <p>
        عنوان رزرو شده
        {{ reserv.post.title }}
    </p>
    <p>
        قیمت نهایی
        {{ reserv.post.price }}
    </p>
    <p>
        آدرس
        {{ reserv.address }}
        شهر
        {{ reserv.city }}
        پلاک
        {{ reserv.plate }}
    </p>
    <p>
        بیمه
        {{ reserv.insurance }}
    </p>
    <p>
        پرداخت شده
        {{ reserv.paid }}
    </p>
    <p>
        قبول شده؟
        {{ reserv.accept }}
    </p>
    <p>
        زمان درخواست
        {{ reserv.created_at }}
    </p>
    <p>
        <form method="post" action="{% url 'app:reservationRequest' reserv.id %}">
            {% csrf_token %}
            <p>
                <input type="submit">
            </p>
        </form>
    </p>
    <p>
        ***************************************************
    </p>

    {% endfor %}

</body>
</html>