Doc2Door/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('app.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from .views import *

app_name = 'app'


urlpatterns = [
    path('home/' ,Home , name='home' ),
    path('contact/' , contact , name="contact"),

    path('logout/' ,Logout_view , name='logout' ),
    path('loginPhone/' , login_phone , name='loginPhone'),
    path('verify_login_phone/' , verify_login_phone , name='verify_login_phone'),
    path('loginPhoneDoctor/' , login_phone_doctor , name='loginPhoneDoctor'),
    path('verify_login_phone_doctor/' , verify_login_phone_doctor , name='verify_login_phone_doctor'),

    path('updateProfile/' , ProfileUpdate ,name='ProfileUpdate'),
    path('profile/' , profile_view ,name='profile'),

    path('post/',postView , name="postView"),
    path('singlePost/<str:slug>' ,singlePost , name='singlePost' ),
    path('category/<str:slug>', category ,name="category"),

    path('news/',newsView , name="newsView"),
    path('singleNews/<str:slug>',singleNews , name="singleNews"),

    path('reservationView/<int:id>' , reservationView , name='reservationView'),
    path('showReservation/' , showReservation , name="showReservation"),
    path('reservationRequest/<int:id>' , reservationRequest , name='reservationRequest'), 
    path('detailReserve/' , detailReserve , name="detailReserve"),
    path('detailUserResreve/' , detailUserResreve , name="detailUserResreve"),
    path('detailDoctor/<int:id>' , detailDoctor , name='detailDoctor'),

    path('deleteCartView/<int:id>' , deleteCartView , name='deleteCartView'),
    path('cartView/' , cartView , name='cartView'),

    path('send_request/', request_payment, name='request'),
    path('verify/', verify , name='verify'),

    path('test/' , test , name='tset')
]

app/templates/app/header/header.html
{% load static %}
<div class="header_section">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="logo"><a href="{% url 'app:home' %}"><img src="{% static 'images/logo.png' %}"></a></div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="تغییر ناوبری">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
           <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                 <a class="nav-link" href="{% url 'app:home' %}">خانه</a>
              </li>
              <li class="nav-item">
                 <a class="nav-link" href="#">سلامتی</a>
              </li>
              <li class="nav-item">
                 <a class="nav-link" href="#">داروها</a>
              </li>
              <li class="nav-item">
                 <a class="nav-link" href="{% url 'app:newsView' %}">اخبار</a>
              </li>
              <li class="nav-item">
                 <a class="nav-link active" href="#">مشتریان</a>
              </li>
              <li class="nav-item">
                 <a class="nav-link" href="#">تماس با ما</a>
              </li>
              <li class="nav-item">
                 <a class="nav-link" href="#"><img src="{% static 'images/search-icon.png' %}"></a>
              </li>
           </ul>
        </div>
     </nav>
  </div>